### ISSUE TITLE
Error updating IPv4 record when IPv6 enabled

### ISSUE THREAD

**Issue by cdalvaro** [timothymiller/cloudflare-ddns#104]
The script is sending the IPv6 value for the IPv4 record

```
⚙️ No config detected for 'ttl' - defaulting to 300 seconds (5 minutes)
🕰️ Updating IPv4 (A) & IPv6 (AAAA) records every 300 seconds
📡 Updating record {'type': 'A', 'name': 'xyz.cdalvaro.io', 'content': '2a0c:5a81:****::275', 'proxied': False, 'ttl': 300}
😡 Error sending 'PUT' request to 'https://api.cloudflare.com/client/v4/zones/*******':
{"result":null,"success":false,"errors":[{"code":9005,"message":"Content for A record must be a valid IPv4 address."}],"messages":[]}
```

Image tag: `latest`, image id: `69c10f49e4b1`

docker-compose.yml

```yml
version: '3.9'

services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    network_mode: host
    volumes:
      - ./config.json:/config.json:ro
    env_file: .env
```

config.json

```json
{
  "cloudflare": [
    {
      "authentication": {
          "api_token": "****"
      },
      "zone_id": "****",
      "subdomains": [
        {
          "name": "xyz",
          "proxied": false
        }
      ]
    }
  ],
  "a": true,
  "aaaa": true,
  "purgeUnknownRecords": false
}
```
