### ISSUE TITLE
Multiple domains via env vars?

### ISSUE THREAD

**Issue by ameeno** [timothymiller/cloudflare-ddns#126]
Hello,

I have seen it is quite possible to update multiple domains/zones via a config json file.
However I would like this container to not rely upon a config file mount to work (docker swarm with multiple hosts)

Right now my portainer stack is this container *3 as its 1 per zone,

and each container is configured via env vars., is it possible to give a single env var with an array for domains? I want to avoid having so many containers running at once.

**Comment by timothymiller** [comment]
It's not necessary to run 3x containers for three zones. One config file can handle three zones' configs. See the README for instructions.

Re: environment variable support in lieu of a config file, I am open to a PR that supports this as long as it is backwards compatible!

**Comment by ameeno** [comment]
Hi Timothy,

Yea, I saw the config file option via a mount, but I am trying to keep this
service/stack without needing a file/volume mounted, so I can easily move
it across the swarm.

Unfortunately docker/compose does not allow inline config files like k8s
does with confmaps so I'm not sure else to do. Perhaps an array of zones
might work?



Best Wishes,

AS.

Sent from a mobile.
Please excuse brevity and typo's
Mob: +44 7877 000 439

**Comment by altano** [comment]
@ameeno I keep my docker-compose configs on my local laptop and use a `DOCKER_CONTEXT` environment variable to remotely execute commands against my Docker host. The downside to this approach is that I'm not setup to have bind mounts of local config files. You can use the same workaround I use if you don't want to mount files/volumes from local configuration: create a Docker image that bundles your configuration, like so:

- Create a new directory for your docker stack, e.g. "cloudflare-ddns"
- Create a docker-compose.yaml file in there
- Create a subdirectory called "cloudflare-ddns-with-config"
- Create a config.json in that subdirectory and a Dockerfile

Your files should look like this:

```
| 📁 cloudflare-ddns
    | 📄 docker-compose.yaml
    | 📁 cloudflare-ddns-with-config
        | 📄 config.json
        | 📄 Dockerfile
```

with the contents being:

cloudflare-ddns/cloudflare-ddns-with-config/config.json:
```
{ ... your config ... }
```

cloudflare-ddns/cloudflare-ddns-with-config/Dockerfile:
```
FROM timothyjmiller/cloudflare-ddns:latest
ADD ./config.json /
```

cloudflare-ddns/docker-compose.yaml:
```
version: "3.9"
services:
  cloudflare-ddns:
    # Instead of using the image directly, use the Dockerfile that bundles the config.json:
    build:
      context: cloudflare-ddns-with-config/
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    restart: unless-stopped
```

Note that `image` and `volumes` are not present in this docker-compose.yaml file!

Then you just `docker compose up --build -d` in the root dir and you're off to the races.
