### ISSUE TITLE
IPv4 & IPv6 not detected. Verify your ISP or DNS provider isn't blocking Cloudflare's IPs.

### ISSUE THREAD

**Issue by Aiakio** [timothymiller/cloudflare-ddns#148]
Im not sure if or what im doing wrong. The container log:

**Describe the bug**
🧩 IPv4 not detected via 1.1.1.1, trying 1.0.0.1
🧩 IPv4 not detected via 1.0.0.1. Verify your ISP or DNS provider isn't blocking Cloudflare's IPs.
🧩 IPv6 not detected via 1.1.1.1, trying 1.0.0.1
🧩 IPv6 not detected via 1.0.0.1. Verify your ISP or DNS provider isn't blocking Cloudflare's IPs.

Cloudflare's IPs are not blocked.

**To Reproduce**
1. Set everything up, according to the instructions
2. Check docker logs to see error

**Expected behavior**
It should get the IPv4 and IPv6.

**Desktop (please complete the following information):**
Docker on Synology NAS, deployed via Portainer stack:
```
 services:
    cloudflare-ddns:
        image: timothyjmiller/cloudflare-ddns:latest
        container_name: cloudflare-ddns
        security_opt:
            - no-new-privileges:true
        network_mode: host
        restart: unless-stopped
        environment:
            - PUID=1026
            - PGID=100
        volumes:
            - /volume1/docker/cloudflare-ddns/config.json:/config.json
```

The config.json looks like this:
```
{
  "cloudflare": [
    {
      "authentication": {
        "api_token": "[REDACTED]"
      },
      "zone_id": "[REDACTED]",
      "subdomains": [
        {
          "name": "",
          "proxied": true
        },
        {
          "name": "[SUBDOMAIN]",
          "proxied": true
        },
        {
          "name": "[SUBDOMAIN]",
          "proxied": true
        }
      ]
    }
  ],
  "a": true,
  "aaaa": true,
  "purgeUnknownRecords": true,
  "ttl": 300
}
```

**Additional context**
Any ideas where the issue might be?
If more information is needed to troubleshoot, ill gladly provide that.
