### ISSUE TITLE
Update failing after internet loss

### ISSUE THREAD

**Issue by archef2000** [timothymiller/cloudflare-ddns#165]
**Describe the bug**
I sometimes losse internet and after that the container never recovers from that and is trowing a authentication error.

**To Reproduce**
1. cut DSL
2. reconnect dsl
3. wait for router
4. see logs

**Expected behavior**
Don't try to update the IP if it is failing to get the ip

**Server:**
 - OS: Ubuntu 22.04

**Comment by cdalvaro** [comment]
A healthcheck would be welcome to test the state of the container.

**Comment by alangrainger** [comment]
Here's a healthcheck you can use.

Add this script `healthcheck.sh` to the same folder as your `docker-compose.yml`:

```bash
#!/bin/sh

# Check to see if the script is running
if ! ps ax | grep [c]loudflare-ddns > /dev/null 2>&1; then
    echo "cloudflare-ddns process not found. Exiting."
    exit 1
fi

# Get the remote IP from Cloudflare debugging page
curl_ip=$(wget -qO - https://one.one.one.one/cdn-cgi/trace | grep '^ip=' | cut -d= -f2)

# Get the IP address for one of our DDNS URLs
dig_ip=$(ping -c 1 YOUR.WEBSITE.HERE | sed -nr 's/.*\((.*)\).*/\1/p')

# Compare the two IP addresses
if [[ "$curl_ip" = "$dig_ip" ]]; then
    echo "DDNS address is correct: $curl_ip"
else
    echo "The IP addresses do not match:"
    echo "Local IP: $curl_ip"
    echo "Cloudflare IP:  $dig_ip"
    exit 1
fi

```

Then update your `docker-compose.yml` to add the healthcheck:

```yaml
    volumes:
      - ./healthcheck.sh:/healthcheck.sh
    healthcheck:
      test: /healthcheck.sh
      interval: 5m
      retries: 1
      start_period: 20s
      timeout: 10s
```
