### ISSUE TITLE
Root domain (example.com) resolution error

### ISSUE THREAD

**Issue by koeltp** [timothymiller/cloudflare-ddns#187]
![image](https://github.com/timothymiller/cloudflare-ddns/assets/2775276/58fc234a-0d68-4ec6-acfa-be725830d97e)
![image](https://github.com/timothymiller/cloudflare-ddns/assets/2775276/e91d40c3-1664-4417-87a7-9da1b2fb0083)
The correct resolution should be @

**Comment by koeltp** [comment]
`   {
            "name": "@",
            "proxied": true
     },`
Even if configured like this, it still resolves to example.com.example.com.

**Comment by koeltp** [comment]
```
  ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: ddns
    security_opt:
      - no-new-privileges:true
    network_mode: 'host'
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./ddns/config.json:/config.json
    restart: unless-stopped
```

docker compose
