### ISSUE TITLE
Docker Container constantly restarting, Error Code 1

### ISSUE THREAD

**Issue by Xopher00** [timothymiller/cloudflare-ddns#22]
I am following along the instructions for running this dynamic DNS client on my Raspberry Pi 4. I generated my own API Token in Cloudflare and made sure to test that it worked. I copied this token along with the Zone ID into the config.json file.

```
"cloudflare": [
    {
      "authentication": {
          "api_token": "redacted"
      },
      "zone_id": "redacted",
      "subdomains": [
        "",
        "my-subdomain"
      ],
      "proxied": false
    }
  ]
}
```

I also made sure that the path to the config.json file was mounted as a volume inside of the Docker.compose.yml file:

```
version: "3.7"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - /pathtoconfig/cloudflare-ddns/config.json:/config.json
    restart: unless-stopped
```

I run ```docker-compose up -d```, and at first it seems that the Docker container is working properly. However after a minute, when I check the status of the docker containers, I see that it has exited with error-code 1.

```
CONTAINER ID        IMAGE                                   COMMAND                  CREATED             STATUS                         PORTS                 NAMES
6fd340e2e47d        timothyjmiller/cloudflare-ddns:latest   "python -u /cloudfla…"   19 minutes ago      Restarting (1) 3 seconds ago                            cloudflare-ddns

```

I try and inspect the docker logs to see what went wrong:
```
docker logs -f cloudflare-ddns
standard_init_linux.go:211: exec user process caused "exec format error"
```
So I am somewhat stumped on this issue. I am running Raspbian 10 on a Raspberry Pi 4
If you have any advice on this problem or if there is something wrong with my configuartion please let me know.
