### ISSUE TITLE
Fatal Python error: init_interp_main: can't initialize time

### ISSUE THREAD

**Issue by kleo** [timothymiller/cloudflare-ddns#46]
**Describe the bug**
Without `privileged: true` on `docker-compose.yml` container just exits with

```Recreating cloudflare-ddns ... done
Attaching to cloudflare-ddns
cloudflare-ddns    | Fatal Python error: init_interp_main: can't initialize time
cloudflare-ddns    | Python runtime state: core initialized
cloudflare-ddns    | PermissionError: [Errno 1] Operation not permitted
cloudflare-ddns    | 
cloudflare-ddns    | Current thread 0x76fb7390 (most recent call first):
cloudflare-ddns    | <no Python frame>
cloudflare-ddns exited with code 1
```

**To Reproduce**
1. Clone repository
2. Setup docker-compose and config

```version: "3.3"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config.json:/config.json
    restart: unless-stopped
```

```
{
  "cloudflare": [
    {
      "authentication": {
          "api_token": "<api_token>", 
          "api_key": {
              "api_key": "api_key_here",
              "account_email": "your_email_here"
                }
      },
      "zone_id": "<zone_id>",
      "subdomains": [
        ""
      ],
      "proxied": false
    }
  ],
  "a": true,
  "aaaa": true
}

```

3. `docker-compose up` see error

**System (please complete the following information):**
 - OS: Raspberry Pi OS Lite January 11th 2021

**Additional context**
Running docker as pi user on Raspberry Pi 3

**Comment by timothymiller** [comment]
Your first docker-compose.yml file contains privileged: true

This is not in the example docker-compose.yml file, please remove it & re-test.

**Comment by kleo** [comment]
Without `privileged:true` it errors out. Error goes away with the following `docker-compose.yml`

```
version: "3.3"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    privileged: true
    security_opt:
      - no-new-privileges:true
    network_mode: "host"
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - ./config.json:/config.json
    restart: unless-stopped
```
