### ISSUE TITLE
Help with "Error reading config.json" -- docker-compose

### ISSUE THREAD

**Issue by Europa2010AD** [timothymiller/cloudflare-ddns#80]
I'm unable to figure out why I keep getting this "error reading config.json" message no matter what I do. Running docker containers on my QNAP, below is my docker-compose .yml using a user-account without admin privileges:
```
version: "3.7"
services:
  cloudflare-ddns:
    image: timothyjmiller/cloudflare-ddns:latest
    container_name: cloudflare-ddns
    security_opt:
      - no-new-privileges:true
    environment:
      - PUID=1001
      - PGID=1001
    volumes:
      - /[path to app directory]/config.json:/config.json
    restart: always
```
I didn't use `network_mode: "host"` because I have no use for IPv6.

Below is my `config.json` file:
```
{
  "cloudflare": [
    {
      "authentication": {
          "api_token": "[my cloudflare token]",
      },
      "zone_id": "[DNS zone 1 ID]",
      "proxied": false
    },
    {
      "authentication": {
          "api_token": "[my cloudflare token]",
      },
      "zone_id": "[DNS zone 2 ID]",
      "proxied": false
    }
  ],
  "a": true,
  "aaaa": false,
  "purgeUnknownRecords": false
}
```
I'm only trying to update the IPs of two different root domains, so I removed the subdomain parts. I've checked and verified that my CF API token has the proper privileges to read zones and edit DNS.

I've tried both creating this `config.json` file using both the admin account that I use to SSH into my server, and using the non-admin account referred to in my docker-compose file. Both returns the same "error reading config.json" message.

What am I doing wrong?
